
language: objective-c

osx_image: xcode12
env:
  matrix:
    - TEST_SDK=iphonesimulator13.0 OS=13.0 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator13.0 OS=13.0 NAME='iPhone 7'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project BitPageControl.xcodeproj -scheme BitPageControl -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
