
osx_image: xcode11.6
language: objective-c
xcode_project: BitPageControl.xcodeproj # path to your xcodeproj folder
xcode_scheme: BitPageControlTests
xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone X
